networks:
  sovet_bot_net:
    driver: bridge
    ipam:
      config:
        - subnet: 172.25.0.0/16


services:  
  db:
    image: postgres:17.1-alpine
    container_name: sovet_bot_db
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust
      - POSTGRES_DB=${DB_NAME:-sovet_bot}
      - POSTGRES_USER=${DB_USER:-sovet_bot}
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $$DB_USER"]
      interval: 5s
      timeout: 5s
      retries: 3
    env_file:
      - .env
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql:ro
    networks:
      - sovet_bot_net

  bot:
    build: .
    container_name: sovet_bot
    depends_on:
      db:
        condition: service_healthy
    env_file:
      - .env
    ports:
      - "8080:8080" 
    networks:
      - sovet_bot_net

volumes:
  pgdata:
